### ISSUE TITLE
[Community] Member profile update

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1090]
**Current Behavior**
[Layer5-ng community member](https://layer5ng.netlify.app/community/members) profiles now have the ability to include a link to their LinkedIn profile.

**Desired Situation**
Update @kalradev's profile to include the following front matter:

```
linkedIn: dev-kalra-b94282160
```

- [Source code](https://github.com/layer5io/layer5/tree/layer5-ng/src/collections/members) of member profiles.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by OlushesiToheeb** [comment]
i want to take this issue

**Comment by kalradev** [comment]
I have changed my LinkedIn profile link.
Now it is - https://www.linkedin.com/in/dev-kalra

**Comment by kishore007k** [comment]
@OlushesiToheeb Did you started working on this?

**Comment by OlushesiToheeb** [comment]
No, Have not started working on it.

**Comment by OlushesiToheeb** [comment]
But I'll. Kindly comment below on the right details to fill in.

**Comment by Nikhil-Ladha** [comment]
I think this issue is resolved already?
@leecalcote , @Tanuj22 , @Jashpatel1

**Comment by leecalcote** [comment]
@Nikhil-Ladha good question. This particular issue remains to be completed - 
![346E4CFD-44D4-448D-BC85-F73AA9111EE9](https://user-images.githubusercontent.com/7570704/100541332-e3ecb480-3208-11eb-9802-d29936201fef.jpeg)

**Comment by OlushesiToheeb** [comment]
> I have changed my LinkedIn profile link.
> Now it is - https://www.linkedin.com/in/dev-kalra

@leecalcote kindly check this and give me the right details so it can be implemented

**Comment by Nikhil-Ladha** [comment]
It is right, you can update it.

**Comment by OlushesiToheeb** [comment]
Okay Thanks @Nikhil-Ladha

**Comment by Jashpatel1** [comment]
@OlushesiToheeb @leecalcote @Nikhil-Ladha Any progress here?

**Comment by OlushesiToheeb** [comment]
my next *PR* will have the updated version

**Comment by Nikhil-Ladha** [comment]
> my next _PR_ will have the updated version

Will your next PR add the LinkedIn profile for all the community members? If they have one?

**Comment by OlushesiToheeb** [comment]
No @Nikhil-Ladha, just this one actually or is there anyone you want me to add on the layer5-ng

**Comment by Nikhil-Ladha** [comment]
What does 'this' refer here?

**Comment by OlushesiToheeb** [comment]
**linkedIn: dev-kalra-b94282160**

**Comment by Nikhil-Ladha** [comment]
Okay, ypu can update that one. Though the updated id is mentioned in the above comments use that one ( https://github.com/layer5io/layer5/issues/1090#issuecomment-723902542).

And, @Jashpatel1 this will solve actually a part of this issue. The bigger issue is adding the LinkedIn profile for all of them, so will you create an 'epic' issue for that?

**Comment by Tanuj22** [comment]
FIxed in #1263
