### ISSUE TITLE
Text is overflowed between 769px and 991px on page: /cloud-native-management/meshmap

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3326]
#### Description
Text is overflowed between 769px and 991px on page: /cloud-native-management/meshmap
![Screenshot 2022-10-15 111618](https://user-images.githubusercontent.com/85894871/195971215-477f2988-e700-4ad6-bc68-b29040f2affb.png)

#### Expected Behavior
![Uploading Screenshot 2022-10-15 112222.png…]()

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Krishna2323** [comment]
**_Expected Behavior_**
![Screenshot 2022-10-15 112222](https://user-images.githubusercontent.com/85894871/195971345-ac9c4bb0-b88a-4bcf-b53d-826648664b53.png)

**Comment by jsvigneshkanna** [comment]
Please assign me this issue

**Comment by AbhishekTiwari23** [comment]
My setup is also ready. Please let me know if I can contribute.

**Comment by legendarykamal** [comment]
@AbhishekTiwari23 go ahead 🎸

**Comment by AbhishekTiwari23** [comment]
@legendarykamal, sir, thanks for assigning me. Can you please check issue numbers #3221 and #3315? I have completed them and waiting for their response.

**Comment by Nikhil-Ladha** [comment]
I don't think the issue is valid as of now. This has already been fixed in #3314

**Comment by Krishna2323** [comment]
@Nikhil-Ladha, the issue is still there......I don't think adding a height of 40rem can fix this, this is something about absolute positioning.

**Comment by Nikhil-Ladha** [comment]
Ok, I just noticed that it is still overflowing ~1000px 😕 .
Adding a media query should fix that, though I am not sure what you mean here by "absolute positioning" 🤔

**Comment by AbhishekTiwari23** [comment]
> Ok, I just noticed it is still overflowing ~1000px 😕 . Adding a media query should fix that, though I am not sure what you mean here by "absolute positioning" 🤔

There are two such issues, and a media query can solve both. I was a bit busy, but I will try to make PR for both by the end of the day.

**Comment by Krishna2323** [comment]
@Nikhil-Ladha, just have to reduce the top property of the heading and for the div containing the image and text as they are positioned absolute.

**Comment by AbhishekTiwari23** [comment]
@Nikhil-Ladha @Krishna2323, can any of you guide me on how to make a setup for the service mesh pattern? I tried but was not able to do that. An issue of that is assigned to me. I asked for help but didn't get any response.

**Comment by AbhishekTiwari23** [comment]
> ![Screenshot 2022-10-18 152940](https://user-images.githubusercontent.com/85894871/196399895-02af7dbb-25ad-41ec-a407-edb00fe7bc14.png) @Nikhil-Ladha, just have to reduce the top property of the heading and for the div containing the image and text as they are positioned absolute.

Oh, I got that. Thanks.

**Comment by UtkarshMishra12** [comment]
@AbhishekTiwari23 Please update

**Comment by AbhishekTiwari23** [comment]
I will update you by the end of the day.

**Comment by leecalcote** [comment]
If you don’t get it today, let’s free up this issue assignment.

**Comment by UtkarshMishra12** [comment]
@AbhishekTiwari23 Please update (last chance)

**Comment by leecalcote** [comment]
Also: 
<img width="996" alt="Screenshot 2023-03-04 at 5 18 49 AM" src="https://user-images.githubusercontent.com/7570704/222897012-cb530ca7-ed70-4cc2-b1f6-e54fa652bca6.png">

@Shivam-AfA please fix.
