### ISSUE TITLE
Increase number of Integration icons in Homepage animation to prevent blank spaces

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#5899]
### Current Behavior

On the homepage (https://layer5.io/), we have an animation of integration icons moving upward in one column and downward in another.
![image](https://github.com/user-attachments/assets/c85ac18f-fbf7-4e79-ae96-f2cf7a3a7de5)

### Desired Situation

The number of icons in the columns is not sufficient, resulting in occasional blank spaces. We should continue showing more integration icons.
Note: we have over 320 integrations found in [collections/integrations](https://github.com/layer5io/layer5/tree/master/src/collections/integrations)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Tharanishwaran** [comment]
I'd like to work on this issue - could you please assign it to me?

**Comment by vaishnaviadhau** [comment]
@vishalvivekm I would like to work on it

**Comment by Ashparshp** [comment]
Thank you, @Tharanishwaran and @vaishnaviadhau.

@Tharanishwaran, since you’re currently assigned to an issue, could you please focus on completing that first? We have several open issues, so feel free to pick any after you're done.
For now, let’s assign this issue to @vaishnaviadhau.

**Comment by Tharanishwaran** [comment]
Hi @Ashparshp,

I appreciate your concern. I want to clarify that I pushed a PR for another issue 5 days ago, but it hasn't been reviewed or merged yet.

I’m ready to take on the new issue about increasing the number of integration icons on the homepage animation as well. I believe I can manage both effectively. Thank you!

**Comment by jay270804** [comment]
Oops, I wanted to pitch for the issue. 

Tho late I would love to get assigned for the issue ! To start my first real opensource contribution.

**Comment by Ashparshp** [comment]
@jay270804, it's all good since it's already been assigned. Let's hunt for more issues — I can throw a few your way if you missed it!

@Tharanishwaran, since this has been assigned to @vaishnaviadhau, let's allow her to solve it. You can drop a comment and tag me on any other issues — we have a bunch of them, and more are being created. I really appreciate your dedication!

**Comment by Tharanishwaran** [comment]
@Ashparshp,Thank you for the clarification! I completely understand and appreciate the direction. I’m happy to focus on other tasks and contribute wherever I can.
If there are any other issues you think would be a good fit for me, please let me know!

**Comment by Ashparshp** [comment]
@Tharanishwaran, glad to hear that! I appreciate your understanding and enthusiasm. I have tagged you in a few issues, please check them out and you can help with those. Don't hesitate to tag me if you'd like any guidance or assistance.

**Comment by Ashparshp** [comment]
@Tharanishwaran, glad to hear that! I appreciate your understanding and enthusiasm. I have tagged you in a few issues, please check them out and you can help with those. Don't hesitate to tag me if you'd like any guidance or assistance.

**Comment by Abhinavagarwa** [comment]
@Ashparshp can i work on this issue please to start my open source journey

**Comment by Tharanishwaran** [comment]
Hi @vaishnaviadhau are you still working on this issue?
