### ISSUE TITLE
Aerospike Kubernetes Operator logo not visible in dark mode

### ISSUE THREAD

**Issue by kishore08-07** [layer5io/layer5#6976]
### Description

In the homepage integrations section cards and also on the [Aerospike Kubernetes Operator integration page](https://layer5.io/cloud-native-management/meshery/integrations/aerospike-kubernetes-operator), the Aerospike Kubernetes Operator logo/icon is not visible when the site is viewed in dark mode. The icon blends into the dark background, making it difficult to identify.

### Current Behavior

In dark mode, the Aerospike Kubernetes Operator logo is either invisible or barely visible due to insufficient contrast with the background.

### Expected Behavior

Replace the current Aerospike Kubernetes Operator logo with a suitable variant (white/yellow) that maintains visibility and proper contrast in dark mode across all relevant sections (homepage integrations and integration details page).

### Screenshots

<img width="1126" height="562" alt="Image" src="https://github.com/user-attachments/assets/8a143ae5-cad8-4b87-9bd1-acfaaef27fe9" />

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by kishore08-07** [comment]
I’d like to work on this issue.
Could someone assign it to me..

**Comment by leecalcote** [comment]
Thanks for raising this. It is an issue, for sure, but the resolution of it is much more complex than meets the eye. The proposed solution won't work. I don't have time to explain the rest to you now, but would certainly like to see a solution arrived at.

**Comment by kishore08-07** [comment]
I’ll look into it further and await your guidance. so we can work towards the right solution

**Comment by leecalcote** [comment]
You'll have to become an intern here in order to be trained on how this can truly be fixed.

**Comment by kishore08-07** [comment]
> You'll have to become an intern here in order to be trained on how this can truly be fixed.

 I understand it’s a challenging fix. I’d definitely be interested in exploring the internship opportunity and would be excited to learn more about it. Happy to continue the conversation on Slack whenever convenient.

**Comment by bashSunny101** [comment]
@leecalcote 
I've figured out how it can be fixed.
Kindly assign it to me

**Comment by bashSunny101** [comment]
@leecalcote @kishore08-07 Hello,

I have fixed the issue related to the Aerospike Kubernetes Operator icon overwrite in the Meshery repository. 

The fix has been implemented in this PR: [meshery/meshery#16053](https://github.com/meshery/meshery/pull/16053)

All commits in the PR are **GPG-signed** and verified on GitHub.

Please review and merge when convenient. This should resolve the problem mentioned in this issue.

Thank you!

**Comment by hamza-mohd** [comment]
@bashSunny101, you’re not listening. These images get overwritten on a nightly basis. No matter what you do to the image on the site, it won’t have a lasting effect. Again, no, you did not fix the issue. Again, your PR will be closed.

The images are not sourced from the other repo. They are sourced from spreadsheet. This is documented inside Meshery contributor guides for Models.

**Comment by hamza-mohd** [comment]
Moreover, changing the color of the logo, is this aloud and goes against the policy of the owners brand guidelines, @bashSunny101

**Comment by hamza-mohd** [comment]
@kishore08-07, if you want an internship, Thant’s great. There are many available. You need to prove that you will be successful if award in an internship. Demonstrate this.

**Comment by bashSunny101** [comment]
@hamza-mohd Okay ,
I'm sorry for the inconvenience caused, as I'm new to open source contribution and this is the first time I saw such behaviour on a web page .
But I'm curious to know how this can be fixed If you or someone could guide me I would be very thankful to you and other maintainers.

Thanks for reading me.
