### ISSUE TITLE
Layout Issue: Significant empty space on Cloud Native Management Meshery page

### ISSUE THREAD

**Issue by Fireentity** [layer5io/layer5#7149]
### Description
On the [Cloud Native Management - Meshery page](https://layer5.io/cloud-native-management/meshery), there is a noticeable layout issue. At a certain point scrolling down the page, there is a large "hole" or vertical gap where no content is rendered. It appears that a component has CSS height/margin issue causing unnecessary space.

### Expected Behavior
The page content should flow continuously without large, unexplained gaps. All components should render visibly, or the spacing should collapse if a section is empty to maintain visual consistency.

### Screenshots

<img width="1264" height="1313" alt="Image" src="https://github.com/user-attachments/assets/d5897c62-b542-4aa4-8f4f-c4d05e71a151" />

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by rishiraj38** [comment]
There’s an existing PR regarding this #7118 . I think there’s a bug because this page runs completely fine locally.

**Comment by leecalcote** [comment]
Thank you for raising this up, @Fireentity. 👍 

Bugs like this are to be treated with urgency. Please -- when issues like this are found, they are a high priority.

Other work needs to stop in order to ensure issues like this are fixed first.

**Comment by Fireentity** [comment]
@leecalcote Ok, then I'm going to prioritize this

**Comment by rishiraj38** [comment]
I think the issue still persists; some image still break the layout. 

<img width="1800" height="1013" alt="Image" src="https://github.com/user-attachments/assets/cf928b89-6b71-4dbb-a742-0f47315bbee7" />

**Comment by Gosling-dude** [comment]
Hi everyone,
I’d like to take a look at this layout gap issue and try to reproduce it in production vs local.
If no one is actively working on it right now, I’ll proceed and share findings (and a PR if I can isolate the fix).
Please let me know if that works.

**Comment by kishore08-07** [comment]
@Gosling-dude, could you please check if this issue still persists?
